# https://docs.gitlab.com/ee/ci/yaml/

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  DEBIAN_MIRROR: http://debian.tu-bs.de/debian/

services:
  - docker:dind

.debian-mirror-template: &add-debian-mirror
  - echo "deb ${DEBIAN_MIRROR} stretch-updates main" >> /etc/apt/sources.list
  - echo "deb-src ${DEBIAN_MIRROR} stretch-updates main" >> /etc/apt/sources.list
  - echo "deb ${DEBIAN_MIRROR} stretch main" >> /etc/apt/sources.list
  - echo "deb-src ${DEBIAN_MIRROR} stretch main" >> /etc/apt/sources.list
  - cat /etc/apt/sources.list

build_test:
    stage: build
    image: docker/compose:debian-1.29.2
    before_script:
      - *add-debian-mirror
      - docker info
      - docker version
      - docker-compose version
      - apt update && apt install make -y
    script:
      - make ENV=main build
      - make test-build
      - tar -czvf ${PWD}/doc_api.tar.gz ./docs/html
      - tar -czvf ${PWD}/doc_main.tar.gz ./docs/build
    artifacts:
      name: "documentation"
      paths:
        - "doc_main.tar.gz"
        - "doc_api.tar.gz"

.setup-deploy-ssh-template: &setup-ssh
  - apk update && apk add openssh-client
  - mkdir -p ~/.ssh
  - echo "PubkeyAcceptedAlgorithms +ssh-rsa" > ~/.ssh/config
  - echo "HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config

deploy-dev:
  stage: deploy
  image: alpine:3.16
  needs: ["build_test"]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make build-dev-clean"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make ENV=dev build-dev"
  only:
  - dev

deploy-main:
  stage: deploy
  image: alpine:3.16
  needs: ["build_test"]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make build-clean"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make ENV=main build"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && cp -r ./docs/html $DOCS_PATH_ASYNC_API"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && cp -r ./docs/build $DOCS_PATH"
  only:
  - main
