# https://docs.gitlab.com/ee/ci/yaml/

stages: # List of stages for jobs, and their order of execution
  - build
  - deploy
  - stressTest

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  DEBIAN_MIRROR: http://ftp.uni-mainz.de/debian/

services:
  - docker:dind

.debian-archiv-template: &add-debian-archiv
  - sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list
  - sed -i 's|security.debian.org|archive.debian.org/|g' /etc/apt/sources.list
  - sed -i '/stretch-updates/d' /etc/apt/sources.list

.debian-mirror-template: &add-debian-mirror
  - echo "deb ${DEBIAN_MIRROR} stretch-updates main" >> /etc/apt/sources.list
  - echo "deb-src ${DEBIAN_MIRROR} stretch-updates main" >> /etc/apt/sources.list
  - echo "deb ${DEBIAN_MIRROR} stretch main" >> /etc/apt/sources.list
  - echo "deb-src ${DEBIAN_MIRROR} stretch main" >> /etc/apt/sources.list
  - echo "deb http://archive.debian.org/debian-archive jessie/updates main" >> /etc/apt/sources.list
  - echo "deb-src http://archive.debian.org/debian-archive jessie/updates main" >> /etc/apt/sources.list
  - cat /etc/apt/sources.list
  - cat /etc/os-release

.debian-install-docker: &add-debian-docker
  #Add Docker's official GPG key:
  - apt-get update
  - apt-get install ca-certificates curl gnupg -y
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  # Add the repository to Apt sources:
  - echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

build_test:
  stage: build
  image: debian:stable-20231030
  before_script:
   # - *add-debian-archiv
   # - *add-debian-mirror
    - *add-debian-docker
    - apt update && apt install make openssl -y
    #- apt update && apt install docker -y
    #- apt update && apt install docker-compose-plugin -y
    - docker info
    - docker version
  script:
    - openssl genrsa -out private_key.pem 2048
    - make ENV=main build
    - sleep 2
    - while [ "`docker inspect -f {{.State.Health.Status}} nlp_api_main_arangodb_1`" != "healthy" ]; do sleep 2; done
    - make ENV=main test-build
    - docker wait nlp_api_main_docs_asyncapi_1
    - docker wait nlp_api_main_docs_sphinx_1
    - tar -czvf ${PWD}/doc_api.tar.gz ./docs/html
    - tar -czvf ${PWD}/doc_main.tar.gz ./docs/build
  artifacts:
    name: "documentation"
    paths:
      - "doc_main.tar.gz"
      - "doc_api.tar.gz"

.setup-deploy-ssh-template: &setup-ssh
  - apk update && apk add openssh-client
  - mkdir -p ~/.ssh
  - echo "PubkeyAcceptedAlgorithms +ssh-rsa" > ~/.ssh/config
  - echo "HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config

deploy-dev:
  stage: deploy
  image: alpine:3.16
  needs: [ "build_test" ]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make build-dev-clean"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && openssl genrsa -out private_key.pem 2048"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make ENV=dev build-dev"
  only:
    - dev

deploy-main:
  stage: deploy
  image: alpine:3.16
  needs: [ "build_test" ]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make build-clean"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && openssl genrsa -out private_key.pem 2048"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make ENV=main build"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && docker wait nlp_api_main_docs_asyncapi_1"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && cp -r ./docs/html $DOCS_PATH_ASYNC_API"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && docker wait nlp_api_main_docs_sphinx_1"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && cp -r ./docs/build/html $DOCS_PATH"
  only:
    - main

stressTest_dev:
  stage: stressTest
  image: alpine:3.16
  needs: [ "deploy-dev" ]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make ENV=dev test-stress-dev"
    - scp -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP:~/nlp_api/test/stress_results.csv stress_results.csv
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && rm test/stress_results.csv"
  only:
    - dev
  artifacts:
    name: "TestResults"
    paths:
      - "stress_results.csv"

stressTest_main:
  stage: stressTest
  image: alpine:3.16
  needs: [ "deploy-main" ]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make ENV=main test-stress"
    - scp -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP:~/nlp_api/test/stress_results.csv stress_results.csv
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && rm test/stress_results.csv"

  only:
    - main
  artifacts:
    name: "TestResults"
    paths:
      - "stress_results.csv"