# https://docs.gitlab.com/ee/ci/yaml/

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  DEBIAN_MIRROR: http://debian.tu-bs.de/debian/

services:
  - docker:dind

.debian-mirror-template: &add-debian-mirror
  - echo "deb ${DEBIAN_MIRROR} stretch-updates main" >> /etc/apt/sources.list
  - echo "deb-src ${DEBIAN_MIRROR} stretch-updates main" >> /etc/apt/sources.list
  - echo "deb ${DEBIAN_MIRROR} stretch main" >> /etc/apt/sources.list
  - echo "deb-src ${DEBIAN_MIRROR} stretch main" >> /etc/apt/sources.list
  - cat /etc/apt/sources.list

build:
  image:
    name: docker/compose:debian-1.29.2
  stage: build
  needs: []
  before_script:
    - *add-debian-mirror
    - docker info
    - docker version
    - docker-compose version
    - apt update && apt install make -y
  script:
    - make build

.setup-deploy-ssh-template: &setup-ssh
  - apk update && apk add openssh-client
  - mkdir -p ~/.ssh
  - echo "PubkeyAcceptedAlgorithms +ssh-rsa" > ~/.ssh/config
  - echo "HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config

deploy-dev:
  stage: deploy
  image: alpine:3.16
  needs: ["build"]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && make build-dev-clean"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make ENV=dev build-dev"
  only:
  - dev

deploy-main:
  stage: deploy
  image: alpine:3.16
  needs: ["build"]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd peer && make build-clean"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd nlp_api && make ENV=main build"
  only:
  - main
