# https://docs.gitlab.com/ee/ci/yaml/

stages:          # List of stages for jobs, and their order of execution
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

services:
  - docker:dind

build:
  image:
    name: docker/compose:debian-1.29.2
  stage: build
  needs: []
  before_script:
    - docker info
    - docker version
    - docker-compose version
    - apt update && apt install make -y
  script:
    - make nlp_services
