# https://docs.gitlab.com/ee/ci/yaml/

stages: # List of stages for jobs, and their order of execution
  - build
  - deploy
  - stressTest

variables:
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: recursive
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  DEBIAN_MIRROR: http://ftp.uni-mainz.de/debian/

services:
  - docker:dind

build_test:
  stage: build
  image: docker:24.0.7-dind
  before_script:
    - apk add --no-cache make
    - docker info
    - docker version
  script:
    - openssl genrsa -out private_key.pem 2048
    - make ENV=main build
    - sleep 2
    - while [ "`docker inspect -f {{.State.Health.Status}} brokerio-arangodb-1`" != "healthy" ]; do sleep 2; done
    - make ENV=main test-build
    - docker wait brokerio-docs_asyncapi-1
    - docker wait brokerio-docs_sphinx-1
    - tar -czvf ${PWD}/doc_api.tar.gz ./docs/html
    - tar -czvf ${PWD}/doc_main.tar.gz ./docs/build
  artifacts:
    name: "documentation"
    paths:
      - "doc_main.tar.gz"
      - "doc_api.tar.gz"

.setup-deploy-ssh-template: &setup-ssh
  - apk update && apk add openssh-client
  - mkdir -p ~/.ssh
  - echo "PubkeyAcceptedAlgorithms +ssh-rsa" > ~/.ssh/config
  - echo "HostKeyAlgorithms +ssh-rsa" >> ~/.ssh/config
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config

deploy-dev:
  stage: deploy
  image: alpine:3.16
  needs: [ "build_test" ]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && make build-dev-clean"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && openssl genrsa -out private_key.pem 2048"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && make ENV=dev build-dev"
  only:
    - dev

deploy-main:
  stage: deploy
  image: alpine:3.16
  needs: [ "build_test" ]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && git fetch"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && git checkout $CI_COMMIT_SHORT_SHA"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && git submodule update --init"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && make build-clean"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && openssl genrsa -out private_key.pem 2048"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && make ENV=main build"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && docker wait brokerio-docs_sphinx-1"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && cp -r ./docs/html $DOCS_PATH_ASYNC_API"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && docker wait brokerio-docs_sphinx-1"
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && cp -r ./docs/build/html $DOCS_PATH"
  only:
    - main

stressTest_dev:
  stage: stressTest
  image: alpine:3.16
  needs: [ "deploy-dev" ]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && make ENV=dev test-stress-dev"
    - scp -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP:~/broker/test/stress_results.csv stress_results.csv
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && rm test/stress_results.csv"
  only:
    - dev
  artifacts:
    name: "TestResults"
    paths:
      - "stress_results.csv"

stressTest_main:
  stage: stressTest
  image: alpine:3.16
  needs: [ "deploy-main" ]
  script:
    - chmod og= $PEER_RSAKEY
    - *setup-ssh
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && make ENV=main test-stress"
    - scp -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP:~/broker/test/stress_results.csv stress_results.csv
    - ssh -i $PEER_RSAKEY $PEER_SERVER_USER@$PEER_SERVER_IP "cd broker && rm test/stress_results.csv"

  only:
    - main
  artifacts:
    name: "TestResults"
    paths:
      - "stress_results.csv"