name: nlp_api
channels:
  - defaults
dependencies:
  - python==3.10.8
  - pip>=22.1.2
  - numpy>=1.23.1
  - pip:
    - Flask==2.3.2
    - flask-socketio>=5.1.1
    - eventlet==0.33.3
    - redis==4.6.0
    - flask_session==0.5.0
    - greenlet==1.1.3.post0
    - nltk>=3.7
    - requests==2.28.1
    - python-socketio[client]==5.8.0
    - pyyaml>=6.0
    - aiohttp>=3.8.3
    - redis==4.6.0
    - tqdm>=4.62.3
    - python-dotenv>=0.21.0
    - matplotlib>=3.4.3
    - pandas>=1.3.4
    - jupyter>=1.0.0
    - python-arango>=7.6.2
    - pycryptodome>=3.18.0
    - urllib3[secure]==1.26.12