name: brokerio
channels:
  - defaults
dependencies:
  - python==3.12.3
  - pip>=22.1.2
  - tqdm>=4.62.3
  - matplotlib>=3.4.3
  - pandas>=1.3.4
  - jupyter>=1.0.0
  - numpy>=1.23.1
  - python-dotenv>=0.19.2
  - pip:
    - docker>=6.1.3
    - -r ./requirements.txt