version: "3"
services:
  transformer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 app.py
    network_mode: host
    volumes:
      - ./model:/app/model
      - ./config:/app/config